### ISSUE TITLE
403 (CoachingSessionExceeded)

### ISSUE THREAD

**Issue by chunjenChen** [timwis/vizwit#184]
I am not sure if it is an issue. I put my charts of wizw.it in a iframe. After it worked several time, I can not get the charts any more. May I know if it is an issue or I hit some kind of limitation?

**Comment by timwis** [comment]
Hi @chunjenChen! That's odd -- do you have a link I can take a look at?

**Comment by chunjenChen** [comment]
Hey Tim,
Thanks for the reply,
I only played with it in my local host.
The situation happened randomly. Sometimes, it works fine. I guess it is not software bug. It maybe is a server issue.
I give you two screen shots for reference, one is run directly from vizw.it. the other one is run from my application by using iframe.
By the way, your works is awesome. Thank you for doing this wonderful job.

Allen

run from vizw.it
http://vizw.it/?gist=c54a266f4a37dff5c7751d8f36e1a24f
it got the

[cid:image001.png@01D21F16.308F87A0]

2. run from the iframe of my application,
[cid:image003.png@01D21F17.D1946D40]

**Comment by timwis** [comment]
Thanks for the kind words! I think the bottom part of your reply may have been cut off because you replied via email. Can you try replying to the thread directly at https://github.com/timwis/vizwit/issues/184 ? By the way, a screenshot would be helpful too. Or maybe you can post the code you're using?

**Comment by chunjenChen** [comment]
Sometimes, I run from vizw.it directly 
http://vizw.it/?gist=c54a266f4a37dff5c7751d8f36e1a24f
it got the

![01](https://cloud.githubusercontent.com/assets/22455905/19137014/fd16e360-8b3e-11e6-9fa4-92fe85b0a1a1.jpg)

2. run from the iframe of my application in my localhost. 
![02](https://cloud.githubusercontent.com/assets/22455905/19137015/fd179d1e-8b3e-11e6-8401-cca4ffd4109d.jpg)

Thank you very much.

**Comment by timwis** [comment]
Oh! I know _exactly_ what that is. GitHub's gist API has a rate limit on it. So if you refresh rapidly, vizwit will fetch the gist every time and you'll eventually hit GitHub's rate limit. Annoying, I know :-/ You can try using [the beta editor](http://vizw.it/editor) to write your configs.

Going to close the issue for now since we know what it is, but feel free to reply with any other questions.

**Comment by chunjenChen** [comment]
Thank you very much.
Allen
